### ISSUE TITLE
KeyError with JSONDecodeError very often

### ISSUE THREAD

**Issue by watchakorn-18k** [Bavarder/baichat-py#1]
If you can't fix it, that's fine, I'm just here to report to you.

**Comment by 0xMRTT** [comment]
Can you send me a full log please ?

**Comment by solstice-gao** [comment]
I also encountered this problem. The reason for this problem is that the API has not yet opened the area where it is located, so the Internet must be accessed through a proxy. Using a proxy will trigger the detection of the API, resulting in no correct return.

 I don't have a solution to this problem yet, does the author have a solution?

**Comment by 0xMRTT** [comment]
That's working fine in [Bavarder](https://bavarder.codeberg.page) (this is why baichat-py has been created). I also experienced some issues with Cloudflare sometimes in the past but now I don't encounter any.

**Comment by 0xMRTT** [comment]
0.3.0 has been released with an improved support of errors and delta loading
